### ISSUE TITLE
--pr-url not including urls for private repo

### ISSUE THREAD

**Issue by charj** [FormidableLabs/pull-report#18]
Hi Guys. 
This is a great little tool, I noticed adding `--pr-url` does not add urls to the output for me.

Command used
```pull-report --pr-url -o ORGANISATION --gh-token TOKEN --gh-user --html USER```

Cheers

**Comment by ryan-roemer** [comment]
Is the token you're using authorized to see private repositories?

**Comment by ryan-roemer** [comment]
Can you try out https://github.com/FormidableLabs/pull-report/pull/19 and see if that fixes the issue there?

We had an apparently longstanding inconsistent-camel-casing bug there...
