### ISSUE TITLE
Allow hiding Private Repos

### ISSUE THREAD

**Issue by petems** [FormidableLabs/pull-report#8]
Add option to hide private repos

**Comment by cbartlett** [comment]
As a work around for this: If you use a token as the auth method, when you generate the token just don't check off any of the additional permissions options and then it will only be able to access public repos. Works like a charm.

**Comment by cbartlett** [comment]
Oh, or you could use your fork... #9 Nice work, thanks! :grin:

**Comment by ryan-roemer** [comment]
@petems -- I've merged your PR and released as `pull-report@0.2.0`. Thanks for all the work!
